services:
  - id: phoenix
    image: boostport/hbase-phoenix-all-in-one:2.0-5.0
    ports:
      - "8765"

  - id: mysql
    image: mysql:5
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306"

  - id: postgres
    image: postgres:10-alpine
    ports:
      - "5432"
dev:
  image: golang:1.11-alpine
  env:
    PHOENIX_HOST: http://phoenix:8765
    MYSQL_HOST: mysql:3306
    POSTGRES_HOST: postgres:5432
  steps:
    - type: script
      name: Install build tools
      options:
        command: apk --no-cache --no-progress add build-base git

  reload:
    - type: script
      name: Run tests
      cwd: /source
      options:
        command: go test -v ./...